#+Title: Build vlabs on Openedx 
#+Author: Sytems Team
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This documnet contains the process of versioning the open-edx labs
  to github.
* Requirement
  1. Version control all [[https://github.com/vlabs-on-openedx][vlabs-on-openedx]] repositories.
  2. Automate importing vlabs courses onto vlabs.ac.in
     
* Implementation
* First Requirement Implementation  
*** Steps to export the lab from open-edx
    - Select the Computer Programming lab from open-edx studio.
    - Go to the [[http://vlabs.ac.in:18010/home/][Vlabs-Openedx-Studio]] to export the lab. 
    - Click on "Tools" which is found in the header part of the page.
    - Select "Export" option from the tools.
    - Click on the download link which is displayed after selecting the
      Export option.
    - Extract the downloaded file and rename it with the appropriate
      lab name to identify easily.
   
*** Steps to version control the labs at github 
    - Go to [[https://github.com/openedx-vlead][Github/OpenEdx-Vlead]] to clone the repository.
    - Clone the lab [[https://github.com/openedx-vlead/open-edx-computer-programming-iiith.git][Computer Programming]].
    - Copy the downloaded lab sources of computer programming lab to
      the github repository of Computer programming lab using the below
      cammand
     
      #+BEGIN_EXAMPLE
      sravanthi@sravanthi:~/Downloads$ cp -rf computer-programming/*
      /home/sravanthi/open-edx-computer-programming-iiith
      #+END_EXAMPLE
     
    - Go to the location of the lab on the terminal and follow the
      below steps to push the sources to github:
     
      #+BEGIN_EXAMPLE
      git status git add * 
      git commit -m "updated the sources" 
      git push origin master
      #+END_EXAMPLE
  
    - Finally enter the github username and password to push the
      sources to git.
    - Version controlling of the lab is completed.
    - Created a new repository with the lab name "Single Board Heater
      system Simulation Virtual Lab" under openedx/vlead.
*** Steps to move the labs from one Organization to another Organization
   - On GitHub, navigate to the main page of the repository.
   - Under the lab repository name, click Settings.
   - Click Transfer.
   - Read the warnings and enter the repository name to confirm that
     you've done so.
   - Type the name of the new owner and click I understand, transfer
     this repo.

** Second Requirement Implementation
***  Automation Script to clone the git repositories and port to Open-edx
**** Script to Clone all github repositories at once from Organization
 
 - Below commad gives the detailed list of all the repositories at [[https://github.com/vlabs-on-openedx][vlabs-on-openedx]] in json format

   #+BEGIN_EXAMPLE
   
    wget https://api.github.com/orgs/vlabs-on-openedx/repos?per_page=200

   #+END_EXAMPLE

 - Extract the lab repo from the json data using python:
   #+BEGIN_SRC python :tangle clone-repos.py

import json
from pprint import pprint
from git import Repo
import sys
   
with open('labs.json') as data_file:    
    data = json.load(data_file)
    for i in range(5):
        repo_name = (data[i]["name"].encode("utf-8"))
        repo = (data[i]["html_url"].encode("utf-8"))
        
       # print("/home/sravanthi/Music/automation-labs/" + repo_name)
        Repo.clone_from(repo, "/home/sravanthi/Music/automation-labs/" + repo_name)
   #+END_SRC
   
 - Clone the github repository to local machine using python

   #+BEGIN_SRC
   
   from git import Repo
   
   Repo.clone_from("https://github.com/vlabs-on-openedx/open-edx-computer-programming-iiith", "/home/sravanthi/Music/automation-labs/computer-programming")
   
   #+END_SRC
   
 - To tar the git repositories using python  

   #+BEGIN_EXAMPLE
   
   import tarfile

   with tarfile.open((data[i]["name"].encode("utf-8")) + ".tar.gz", "w:gz" ) as tar:
    for name in os.listdir("/home/sravanthi/Videos/automation-labs-tar"):
        tar.add(name)

   #+END_EXAMPLE

 - Download the files from web using wget in python
   #+BEGIN_EXAMPLE
   
   import os 

   os.system("wget https://api.github.com/orgs/vlabs-on-openedx/repos?per_page=92")
   
   #+END_EXAMPLE
